# Generated by Django 5.1.6 on 2025-04-25 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=50, unique=True)),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[("to'lmagan", "To'lmagan"), ("to'lgan", "To'lgan")], default="to'lmagan", max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Axlat idishi',
                'verbose_name_plural': 'Axlat idishlari',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
            },
        ),
        migrations.CreateModel(
            name='BinStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[("to'lmagan", "To'lmagan"), ("to'lgan", "To'lgan")], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clean_area.bin')),
            ],
            options={
                'verbose_name': 'Status tarixi',
                'verbose_name_plural': 'Status tarixlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bin',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='clean_area.location'),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='clean_area.district')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='clean_area.neighborhood'),
        ),
    ]
